version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres-offboarding
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: offboarding_db
    ports:
      - "5060:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  backend:
    build: ./Backend
    container_name: backend-offboarding
    ports:
      - "3093:3093"
    depends_on:
      - postgres
    environment:
      - PGUSER=postgres
      - PGPASSWORD=admin123
      - PGDATABASE=offboarding_db
      - PGHOST=postgres
      - PGPORT=5432
    volumes:
      - ./Backend/uploads:/app/uploads
    restart: unless-stopped

  employee-offboarding:
    build: ./Employee-Offboarding
    container_name: employee-offboarding
    ports:
      - "9057:80"
    depends_on:
      - backend
    restart: unless-stopped

  hr-offboarding:
    build: ./HR-Offboarding
    container_name: hr-offboarding
    ports:
      - "9058:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres-data:

